<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = PATH_site;

return array(
    'MASK\\Mask\\' => array($typo3InstallDir . 'typo3conf/ext/mask/Classes'),
    'THREEME\\Threeme\\' => array($typo3InstallDir . 'typo3conf/ext/threeme/Classes'),
);
